language: python
python:
  - 3.8
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
# command to run tests
script:
  - black --check .
  - flake8 .
  - coverage run ./manage.py test polls
after_script:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-481958014875"
  on:
    branch: main
